### ISSUE TITLE
XInputJoystickEmu.cpp の FXInputJoystickEmu::EventAnalog の実装につきまして

### ISSUE THREAD

**Issue by mvyoshida** [katze7514/UEDirectInputPadPlugin#1]
XInputJoystickEmu.cpp の 531行目ですが、

```c++
if(XIName==FGamepadKeyNames::LeftTriggerAnalog || XIName==FGamepadKeyNames::LeftTriggerAnalog)
```
XIName との比較が両方共 LeftTriggerAnalog になっています。
片方は RightTriggerAnalog ではないでしょうか？

※DUALSHOCK 4 の入力取得をしたくこちらを利用したところ、
パッドの入力を行わなくてもZ軸負の方向にビューポートのカメラが移動しており、
原因を確認していたらこちらの問題を見かけました。
上記の変更を行うことで入力がない状態で勝手にカメラが動く挙動も起きなくなっています。

**Comment by katze7514** [comment]
返信が遅れてすみません。

ご指摘の通りです。
修正しておきます。
