### ISSUE TITLE
Set Key Map の Negative が期待動作しない

### ISSUE THREAD

**Issue by usagi** [katze7514/UEDirectInputPadPlugin#5]
## 状況

Set Key Map ノードで `Negative` をチェックしても出力が反転しない。

## 期待動作

下図のようにノードを設定した場合、`Negative` の on/off により右スティックのY軸の上下が逆方向に出力されるようになる。

![image](https://user-images.githubusercontent.com/115972/44291633-8b54b000-a2ba-11e8-98f1-219612455b84.png)

## 問題の動作

`Negative` の on/off によらず常に出力方向が変わらない。

## この問題の具体的な影響

ユーザーがゲーム内のコンフィグレーション等で行うリバース設定と実際の動作が、接続するコントローラーによっても変化してしまう可能性が生じる。また、この問題の報告は次に記載するように比較的メジャーで一般的なゲームパッドで発生した事から、影響範囲も小さくない可能性がある。

## この問題の応急措置としての対処方法

本プラグインのユーザー開発者がコントローラーの接続を実行時にチェックするコードと、軸の入力を反転させる係数をかけるコードを追加する。

## 状況の検証または再現に必要な可能性のある条件

1. PS4 の DualShock4 コントローラー（ CUH-ZCT2J ）を USB ケーブルまたは Bluetooth で接続し本プラグインで制御可能としたた状態
2. UE-4.19.2 でプロジェクトを作成

-----

以上、端的にチケットを投げましたが、本プラグインのおかげさまで UE4 標準の Windows RawInput で生じた面倒そうな問題も起こらずに本件を除き快適に使用させて頂けております。もののついでに謝意を。ありがとうございます😃

**Comment by katze7514** [comment]
丁寧なissueありがとうございます。

わかりにくくて申し訳ありません。

`SetKeyMap`ノードの`Negative`は軸の反転に使うものではありません。
軸の反転は、`SetAixsReverse`ノードをご利用ください。

`Nagative`は、

- 軸をボタンに割り合てる時に、軸の正負方向のどちらにするか
- ボタンを軸に割り当てる時に、ボタンが押されている時に軸の正負どちらか

を割り当てるものとなっています。
それ以外の場合は、無視される引数です。

具体的には、

- X軸の負方向を1ボタンに割り当てる際にon
- 3ボタンをY軸の負方向に割り当てる際にon

とするような使い方となります。

**Comment by usagi** [comment]
ぉー、私が機能を勘違いしていたんですねー。失礼しました😭

丁寧な解説を頂けたおかげでプラグインの仕様に基づいて期待動作の組み込み、また勘違いしてしまった機能の本来の用途も理解できました。ありがとうございます。

![image](https://user-images.githubusercontent.com/115972/44304169-3b93e880-a38f-11e8-9b64-f26de2874cc8.png)
